Vahe1994/AQLM

inference_lib/setup.cfg, inference_lib/src/aqlm/__init__.py, inference_lib/src/aqlm/inference.py, inference_lib/src/aqlm/inference_kernels/__init__.py, inference_lib/src/aqlm/inference_kernels/cuda_kernel.cpp, inference_lib/src/aqlm/inference_kernels/cuda_kernel.py, inference_lib/src/aqlm/inference_kernels/dequantization.py, inference_lib/src/aqlm/inference_kernels/kernel_selector.py, inference_lib/src/aqlm/inference_kernels/triton_kernel.py
This PR aims to:
* Add support for backward passes enabling [Adapter Training](https://huggingface.co/docs/peft/index).
* Optimize kernel selection to:
*  Allow to select optimal kernels for training/inference.
* Select kernels once to not run selection on each forward pass.
=> Integrating with `autograd`, adding static kernel routing.

main.py, src/aq.py, src/finetune.py, src/modelutils.py
=> Add mixtral support

inference_lib/setup.cfg, inference_lib/src/aqlm/inference.py, inference_lib/src/aqlm/inference_kernels/kernel_selector.py, inference_lib/src/aqlm/inference_kernels/numba_kernel.py
Right now, `aqlm` requires one to load models with
```python
with aqlm.optimize_for_training():
model = AutoModelForCausalLM.from_pretrained(...)
```
to use kernels optimized for larger batch sizes. It doesn't need to be that way since it's pretty easy to tell which kernels should be used by just looking at the input.
This PR does that.
=> Dynamic kernel selection for traning/inference

inference_lib/setup.cfg, inference_lib/src/aqlm/inference_kernels/cuda_kernel.cpp, inference_lib/src/aqlm/inference_kernels/cuda_kernel.cu, inference_lib/src/aqlm/inference_kernels/kernel_selector.py
This PR should allow one to run 1x16 AQLM in `bfloat16`.
=> Native support for Bfloat16 for 1x16 and 2x8 CUDA kernels

inference_lib/setup.cfg, inference_lib/src/aqlm/inference_kernels/cuda_kernel.cu
`bfloat16` is not supported on T4 and GPU with the same or lower Compute Capability, meaning the kernels will throw an error compiling.
This PR isolates the code behind CC check and throws a runtime error if kernel is not available.
=> `__CUDA_ARCH__<=8.0`  compilation error fix.

README.md, convert_to_hf.py, finetune.py, main.py, src/aq.py, src/finetune.py, src/modelutils.py, src/utils.py
In this pull request following features are added:
- full finetuning with teacher logits
- validation loss is tracked instead of the rate of loss change on validation
- gemma models support
=> Added global funetuning & validation loss early stopping & gemma support

main.py
The PR fixes the rare error  that occurs if nsamples is not specified, e.g. when the main.py is ran for the purpose of evaluaiton
To reviewer: if you believe that the PR can be merged, please merge this by yourself (i.e. without checking with me).
=> Typo: check if nsamples is None

README.md, finetune.py, lmeval.py, main.py, src/modelutils.py
This PR introduces an option to resume calibration from partially quantized model, with the following use cases
- when quantizing a particularly large model (looking at you, grok!), you may run the job every night and stop it during daytime to free GPUs for other tasks
- if the original run crashed due to OOM or other means, one can resume without losing (almost) any progress
- when calibrating on preemptible hardware (e.g. spot instances), one can begin training on one server, then switch to another server when the first one is preempted.
- when calibration went well for most layers, but then loss exploded at *some* layer close to the end (e.g. due to too large an LR), one can change parameters and re-train from that layer on
To this end, the PR introduces two new options to `main.py`:
- …
=> Option to resume previously interrupted calibration, fix edge cases

src/datautils.py
Noticed by @BlackSamorez 
If we use wikitext as *training* data, the code would previously fail, because it uses an old (incompatible) dataset format:
```
(base) jheuristic@ultramar:/home/jheuristic/AQLM$ git pull && TRANSFORMERS_CACHE="/mnt/LLM/hub" OMP_NUM_THREADS=16 MKL_NUM_THREADS=16 CUDA_VISIBLE_DEVICES=5 python main.py "TinyLlama/TinyLlama-1.1B-interm
ediate-step-1431k-3T" "wikitext2" --dtype float16 --relative_mse_tolerance=0.01 --nsamples=2048 --val_size=256 --model_seqlen=2048 --num_codebooks=2 --nbits_per_codebook=8 --beam_size=8 --in_group_size=8
--wandb --finetune_keep_best --finetune_batch_size=64 --local_batch_size=4 --finetune_early_stop=3 --finetune_max_epochs=50
wandb: Currently logged in as: justheuristic (hivemind_cv). Use `wandb login --relogin` to force relogin
wandb: …
```
=> Make old *training* datasets compatible again

README.md, finetune.py, src/modelutils.py, src/utils.py
Summary of changes:
1) Fixed bug that leads to device mistmatch in `finetune.py`
2) Added tuning in bfloat16 that may reduce memory usage. 
3) Removed `--temperature` argument.
Below mem usage for several options is shown.
<google-sheets-html-origin>
dtype | amp | checkpoint | Max Mem Alloc (GB) | Max Mem Res (GB)
-- | -- | -- | -- | --
float32 | N | Y | 51.61 | 57.91
float32 | Y | Y | 51.26 | 57.91
bfloat16 | N | Y | 44.66 | 62.41
=> Fixed device placement for Llama-2 and added tuning in bfloat16

main.py, src/finetune.py
**🔥Quantization on CPU**
I was able to run the quantization on CPU with tiny LLama and red_pajama dataset.
Here are some small remark I made to fix some bugs including:
* When we dont have GPU devices we should add only one device: cpu in the array of devices
* We should use pin_memory only when GPU is available
* We should delete the following assert:
```
assert train_inps[i].is_pinned() and train_outs[i].is_pinned()
```
because it does not make sense since we do not use pinned memory without GPU.
=> Bug fix for CPU quantization

src/aq.py
I've checked, and it works with Llama2-7b model
=> Reduced memory footprint by storing codes in torch.int32

src/datautils.py
Legacy workaround for some versions of Llama-1 leads to failure when attempting to quantize Llama-3 model that has only `LlamaFastTokenizer`. I propose to remove it.
=> Removed legacy workaround for Llama

finetune.py, main.py
This way variables won't leak into scopes of other functions.
We've already [encountered](https://github.com/Vahe1994/AQLM/pull/69/files#diff-a5ff12394959301eb25d323d44fc987a79336e66a44eb3e4def7ae3515f35430R48) a bug because of this.
Official python documentation [advices](https://docs.python.org/3/library/__main__.html#idiomatic-usage) to write code this way just for that reason
> This is error-prone as other functions within the module could be unintentionally using the global variable instead of a local name. A main function solves this problem.
=> moved code from if __name__ == "__main__" to main function.

README.md
Previously, the explanation would suggest using --keyword arguments but the script does not accept them. It also had an unfinished sentence at the end. This PR finishes the paragraph and clarifies the usage.
=> Fix formatting and better explain model conversion

README.md
=> Added instructions for creating pv-tuning dataset

inference_lib/src/aqlm/inference.py
See #136.
Use `typing.Any` instead. `torch.Any` fails with torch 2.5.
=> FIX: Type annotation torch.Any

inference_lib/src/aqlm/inference_kernels/cuda_kernel.cu
Currently, 2x8 configuration does not work on Turing GPUs because of the limited [maximum amount of shared memory per SM](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#features-and-technical-specifications-technical-specifications-per-compute-capability) available on the Compute Capability 7.5.
This PR adds Kx8 inference CUDA kernels and uses them as a fallback for the 2x8 configuration on Turing GPUs.
Thus, this configuration can be run on T4, which is the default Google Colab GPU.
Moreover, these kernels can also be used later to infer any Kx8 configuration.
This PR also integrates patch from https://github.com/Vahe1994/AQLM/pull/139.
[Example notebook](https://colab.research.google.com/drive/1uhKjtblkWFrMu2RhSBz5cUkHaXi9TDsG?usp=sharing)
=> Add Kx8 inference kernels

inference_lib/src/aqlm/inference_kernels/cuda_kernel.cpp, inference_lib/src/aqlm/inference_kernels/cuda_kernel.cu, inference_lib/src/aqlm/inference_kernels/cuda_kernel.py, inference_lib/src/aqlm/inference_kernels/kernel_selector.py
This PR adopts existing Kx8 kernels for inference of `ISTA-DASLab/Llama-2-7b-AQLM-PV-2Bit-2x8-hf` model.
Colab example: [link](https://colab.research.google.com/drive/1tGlv1VRAPEusiukGX2ObThc3TRkQfVSC?usp=sharing).
=> Support 1bit-1x8 configuration

inference_lib/src/aqlm/inference.py, inference_lib/src/aqlm/inference_kernels/kernel_selector.py
The triton kernel also works on Intel XPU and could bring 10x speed-up compared to pytorch implementation.
=> enable triton kernel on XPU
